/* QUERIES CURRENTLY RUNNING */
SELECT DISTINCT
[SOURCE] = UPPER(PROGRAM_NAME),
[DATABASE] = UPPER(D.NAME),
[USER] = UPPER(NT_USERNAME),
[ID] = P.SPID,
LAST_BATCH = CONVERT(CHAR(10),LAST_BATCH,101),
[TIME] = LEFT(RIGHT(CONVERT(VARCHAR,DATEADD(MS,DATEDIFF(MS, P.LAST_BATCH,GETDATE()),'1900-01-01'),121),12),8),
STATUS = UPPER(P.STATUS),
CMD,
[SQL] = SQLTEXT.TEXT
--SELECT TOP 100 *
FROM MASTER..SYSPROCESSES P
LEFT JOIN MASTER..SYSDATABASES D
ON P.DBID = D.DBID
CROSS APPLY SYS.DM_EXEC_SQL_TEXT(SQL_HANDLE) AS SQLTEXT 
WHERE P.STATUS NOT IN ('SLEEPING')
ORDER BY [TIME] DESC
